# Generated by Django 5.2.5 on 2025-10-16 03:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(120)])),
                ('visited_places', models.TextField(blank=True, help_text='Lugares que has visitado (uno por línea o separados por comas)')),
                ('budget_preference', models.CharField(choices=[('0-500', '$0 - $500'), ('500-1000', '$500 - $1,000'), ('1000-2000', '$1,000 - $2,000'), ('2000-3000', '$2,000 - $3,000'), ('3000-5000', '$3,000 - $5,000'), ('5000+', '$5,000+')], default='500-1000', max_length=20, verbose_name='Preferencia de presupuesto')),
                ('interests', models.CharField(blank=True, help_text='Eventos de interés separados por comas', max_length=200)),
                ('biography', models.TextField(blank=True, max_length=500, verbose_name='Biografía')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
