# Generated by Django 5.2.5 on 2025-10-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='visited_places',
            field=models.TextField(blank=True, help_text='Lugares que has visitado (uno por línea o separados por comas.)'),
        ),
    ]
