# Generated by Django 5.2.5 on 2025-10-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_userprofile_visited_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre del Lugar')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='places_photos/', verbose_name='Foto Principal')),
                ('short_description', models.CharField(help_text='Descripción corta para las tarjetas', max_length=200, verbose_name='Descripción Breve')),
                ('events', models.CharField(blank=True, help_text='Eventos disponibles en el lugar', max_length=500, verbose_name='Eventos')),
                ('restaurants', models.CharField(blank=True, help_text='Restaurantes recomendados', max_length=500, verbose_name='Restaurantes')),
                ('hotels', models.CharField(blank=True, help_text='Hoteles cercanos', max_length=500, verbose_name='Hoteles')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Estimado')),
                ('category', models.CharField(blank=True, help_text='Ej: Playa, Montaña, Cultural', max_length=100, verbose_name='Categoría')),
                ('rating_average', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Calificación Promedio')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
                'ordering': ['-rating_average', 'name'],
            },
        ),
    ]
